name: Pre Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]-pre[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup nodeJs to 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract package version
        id: version
        run: echo ::set-output name=version::$(npm run get-version --silent)

      - name: Install npm dependencies
        run: npm install

      - name: Build package
        run: npm run prepack

      - name: Publish package to npm
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/sylcastaing/maintenance-page-generator/mpg-builder:${{ steps.version.outputs.version }}
          build-args: |
            version=${{ steps.version.outputs.version }}

      - name: Create Pre Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
