name: Pre Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]-pre[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Get package version
        id: version
        run: echo ::set-output name=version::$(npm run get-version --silent)
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run prepack
      - name: Publish
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: ${{ steps.version.outputs.version }}
          build_args: |
            version=${{ steps.version.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
